#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MovieDB.Droid.Resource", IsApplication=true)]

namespace MovieDB.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int darkgray = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int largeText = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int mediumText = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int smallText = 2130968581;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int customratingbar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rate_star_big_half = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rate_star_big_off = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rate_star_big_on = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int test = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int login_password = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int login_signin = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int login_username = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int moviedetail_addtofavorites = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int moviedetail_layout = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int moviedetail_movieimage = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int moviedetail_overview = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int moviedetail_playvideo = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int moviedetail_rating = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int moviedetail_releasedate = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int moviedetail_scrollview = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int moviedetail_similarmoviesgrid = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int moviedetail_similartitle = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int moviedetail_title = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int moviedetail_titleinfolayout = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int moviedetail_toplayout = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int moviedetail_totalvotes = 2131034124;
			
			// aapt resource value: 0x7f050012
			public const int movieitem_image = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int movierow_item = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int movierow_title = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int movies_recyclerView = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int similarmovieitem_image = 2131034134;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int moviedetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int movieitem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int movierow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int movies = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int similarmovieitem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int Email = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int LoginMessage = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int NowPlaying = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int Password = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int PlayVideo = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int Popular = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int RemoveFavorites = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int SaveToFavorites = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int SignIn = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int SimilarMovies = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int TopRated = 2131165189;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int EditText = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int MainTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int SpinnerStyle = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int ratingBar = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
